{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cas-service.fullname" . }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end -}}
{{- end -}}