apiVersion: v1
kind: Service
metadata:
  name: {{ include "cas-service.fullname" . }}
  labels:
    {{- include "cas-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
      {{- include "cas-service.nodePort" . | nindent 6 }}
  selector:
    {{- include "cas-service.selectorLabels" . | nindent 4 }}
